stages:
    - build_and_run

image: ${IMAGE}

build-image:
    stage: build_and_run
    variables:
        TAG: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
    script:
        - echo ${CI_BUILD_TOKEN} | docker login --username gitlab-ci-token --password-stdin ${CI_REGISTRY}
        - docker build --no-cache -t "${TAG}" -f Dockerfile .
        - docker run --user $(id -u):$(id -g) --group-add 100 
          -v $(pwd)/test_data/:/input/ -v $(pwd):/output/ 
          ${TAG} 
          --help
        - docker tag "${TAG}" "${CI_REGISTRY_IMAGE}:latest"
        - docker push "${CI_REGISTRY_IMAGE}:latest"
