include:
    - project: "epi2melabs/ci-templates"
      file: "wf-containers.yaml"

variables:
    NF_WORKFLOW_OPTS: "--prefix test --fastq test_data/fastq --references test_data/references --counts test_data/counts/ERCC_mix1.csv --threads 2"
