name: epi2melabs-wf-alignment
channels:
    - epi2melabs
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python==3.8.*
    - aplanat==0.5.4
    - pysam
    - mapula
    - barcoder
    - minimap2
    - samtools
    - scikit-learn
    - fastcat==0.3.8
    - mosdepth==0.3.1
    - bamtools
    - bedtools
    - seqkit
