name: epi2melabs-wf-alignment
channels:
    - epi2melabs
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python==3.8.*
    - aplanat
    - pysam
    - mapula
    - barcoder
    - minimap2
    - samtools
    - scikit-learn
    - fastcat==0.4.10
    - mosdepth==0.3.1
    - bamtools
    - bedtools
    - seqkit
    - epi2melabs