name: epi2melabs-wf-alignment
channels:
    - epi2melabs
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python==3.8.*
    - aplanat
    - pysam
    - mapula
    - barcoder
    - minimap2
    - samtools==1.15
    - scikit-learn
    - fastcat
    - mosdepth
    - bamtools
    - bedtools
    - seqkit
    - epi2melabs
    - gzip
